version: '3.1'

networks:
  corp:
    driver: bridge

services:
  api:
    container_name: lazy-api
    networks:
      - corp
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - 3333:3333
    volumes:
      - "./apps:/usr/src/app/apps:ro"
      - "./libs:/usr/src/app/libs:ro"
  app:
    networks:
      - corp
    build:
      context: .
      dockerfile: client.dockerfile
    ports:
      - 4200:4200
    command: npx ng serve --host 0.0.0.0
    volumes:
      - "./apps:/usr/src/app/apps:ro"
      - "./libs:/usr/src/app/libs:ro"
  db:
    image: postgres
    restart: always
    networks:
      - corp
    environment:
      POSTGRES_PASSWORD: example
